use serde::{Deserialize, Serialize};

#[derive(Deserialize, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Field {
	pub aggregatable: bool,
	pub ai_prediction_field: bool,
	pub auto_number: bool,
	pub byte_length: u32,
	pub calculated: bool,
	pub calculated_formula: Option<String>,
	pub cascade_delete: bool,
	pub case_sensitive: bool,
	pub compound_field_name: Option<String>,
	pub controller_name: Option<String>,
	pub createable: bool,
	pub custom: bool,
	//    pub default_value: Option<String>,
	pub default_value_formula: Option<String>,
	pub defaulted_on_create: bool,
	pub dependent_picklist: bool,
	pub deprecated_and_hidden: bool,
	pub digits: u8,
	pub display_location_in_decimal: bool,
	pub encrypted: bool,
	pub external_id: bool,
	pub extra_type_info: Option<String>,
	pub filterable: bool,
	pub filtered_lookup_info: Option<String>,
	pub formula_treat_null_number_as_zero: bool,
	pub groupable: bool,
	pub high_scale_number: bool,
	pub html_formatted: bool,
	pub id_lookup: bool,
	pub inline_help_text: Option<String>,
	pub label: String,
	pub length: u32,
	pub mask: Option<String>,
	pub mask_type: Option<String>,
	pub name: String,
	pub name_field: bool,
	pub name_pointing: bool,
	pub nillable: bool,
	pub permissionable: bool,
	//    pub picklist_values: [],
	pub polymorphic_foreign_key: bool,
	pub precision: u8,
	pub query_by_distance: bool,
	pub reference_target_field: Option<String>,
	//    pub reference_to: [],
	pub relationship_name: Option<String>,
	pub relationship_order: Option<String>,
	pub restricted_delete: bool,
	pub restricted_picklist: bool,
	pub scale: u8,
	pub search_prefilterable: bool,
	pub soap_type: String,
	pub sortable: bool,
	#[serde(rename = "type")]
	pub field_type: String,
	pub unique: bool,
	pub updateable: bool,
	pub write_requires_master_read: bool,
}
